"""
The evaluation cases and their ground truth.

Sixteen synthetic Terraform plans, each with a verdict decided by hand before any
system was run against it, and each label tied to a numbered rule in
docs/VERDICT_POLICY.md. Nothing in here was generated by a model.
"""

import json
import os
from dataclasses import dataclass, field
from typing import List, Optional

from . import policy
from .plan import Plan, load_plan

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR = os.path.join(_PROJECT_ROOT, "data")
CASES_FILE = os.path.join(DATA_DIR, "cases.json")
PLANS_DIR = os.path.join(DATA_DIR, "plans")


@dataclass
class Case:
    id: str
    plan_file: str
    title: str
    expected_verdict: str
    rules: List[str] = field(default_factory=list)
    difficulty: str = "medium"
    critical_resource: Optional[str] = None
    why: str = ""

    @property
    def plan_path(self) -> str:
        return os.path.join(PLANS_DIR, self.plan_file)

    def load(self) -> Plan:
        return load_plan(self.plan_path)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "plan": self.plan_file,
            "title": self.title,
            "expected_verdict": self.expected_verdict,
            "rules": self.rules,
            "difficulty": self.difficulty,
            "critical_resource": self.critical_resource,
            "why": self.why,
        }


def load_cases(path: str = CASES_FILE) -> List[Case]:
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)

    cases = []
    for entry in payload["cases"]:
        verdict = policy.normalise(entry["expected_verdict"])
        if not verdict:
            raise ValueError(
                "Case %s has an expected_verdict that is not one of the three: %r"
                % (entry.get("id"), entry.get("expected_verdict"))
            )
        cases.append(
            Case(
                id=entry["id"],
                plan_file=entry["plan"],
                title=entry.get("title", ""),
                expected_verdict=verdict,
                rules=list(entry.get("rules") or []),
                difficulty=entry.get("difficulty", "medium"),
                critical_resource=entry.get("critical_resource"),
                why=entry.get("why", ""),
            )
        )
    return cases
